plentymarkets/plenty-plugin-elastic-export

src/Generators/BasicPriceSearchEngine.php, src/Generators/BeezUp.php, src/Generators/BelboonDE.php, src/Generators/BilligerDE.php, src/Generators/CdiscountCOM.php, src/Generators/Check24DE.php, src/Generators/EcondaDE.php, src/Generators/FashionDE.php, src/Generators/GeizhalsDE.php, src/Generators/GoogleShopping.php, src/Generators/GuenstigerDE.php, src/Generators/IdealoDE.php, src/Generators/KaufluxDE.php, src/Generators/KelkooBasicDE.php, src/Generators/KelkooPremiumDE.php, src/Generators/KuponaDE.php, src/Generators/MyBestBrandsDE.php, src/Generators/PreisRoboterDE.php, src/Generators/RakutenDE.php, src/Generators/SchuheDE.php, src/Generators/ShippingProfiles.php, src/Generators/Shopping24DE.php, src/Generators/ShoppingCOM.php, src/Generators/ShopzillaDE.php, src/Generators/TracdelightCOM.php, src/Generators/TreepodiaCOM.php, src/Generators/TwengaCOM.php, src/Generators/ZanoxDE.php
=> FIX - generateContent interface

src/Generators/BasicPriceSearchEngine.hh, src/Generators/BeezUp.hh, src/Generators/BelboonDE.hh, src/Generators/BilligerDE.hh, src/Generators/Check24DE.hh, src/Generators/FashionDE.hh, src/Generators/GeizhalsDE.hh, src/Generators/GoogleShopping.hh, src/Generators/GuenstigerDE.hh, src/Generators/KaufluxDE.hh, src/Generators/KelkooBasicDE.hh, src/Generators/KelkooPremiumDE.hh, src/Generators/KuponaDE.hh, src/Generators/PreisRoboterDE.hh, src/Generators/SchuheDE.hh, src/Generators/Shopping24DE.hh, src/Generators/ShoppingCOM.hh, src/Generators/ShopzillaDE.hh, src/Generators/TracdelightCOM.hh, src/Generators/TreepodiaCOM.hh, src/Generators/TwengaCOM.hh, src/Generators/ZanoxDE.hh, src/Helper/ElasticExportHelper.hh
@plentymarkets/team-multichannel-koboldmaki 
default shipping cost fix für geizhals f#22569
=> quickfix for the default shipping cost for geizhals

src/Generators/RakutenDE.hh
=> FIX logic could not work with vatId but with vatValue

src/Generators/BilligerDE.hh, src/Helper/ElasticExportHelper.hh, src/ResultFields/BilligerDE.hh
=> FIX it is now possible to export variations to billigerDE

src/Generators/GoogleShopping.hh
=> FIX producer is not working, using the helper with producerId instead

src/Generators/RakutenDE.php, src/Helper/ElasticExportHelper.php
@plentymarkets/team-multichannel
=> FIX internal error php7.

src/Generators/IdealoDE.hh
@Desentyer aka BIPPIG:
Migration?
=> FIX create idealoDK SKU when exported

src/Generators/GoogleShopping.php
@plentymarkets/team-multichannel-koboldmaki @tudor2004
=> FIX google shopping attributes

src/Generators/RakutenDE.php
Voraussetzung ist https://github.com/plentymarkets/php-pl/pull/913
=> FIX add the primary variation as first entry

src/Helper/ElasticExportHelper.php
=> FIX internal error

src/Generators/GoogleShopping.php
=> fixed shippingcost for googleshopping

src/Generators/BeezUp.php
=> CHANGE the variationAttributes array creation

src/Generators/IdealoDE.php, src/Helper/ElasticExportHelper.php
=> fixed shippingcost for idealo

src/Generators/IdealoDE.php
=> FIX check if CheckoutApproved character is set

src/Generators/IdealoDE.php
=> FIX build productive error

src/Generators/GoogleShopping.php
@plentymarkets/team-multichannel-koboldmaki 
we forgot the pagination
=> googleshopping attribute fix

src/Helper/ElasticExportHelper.php
@plentymarkets/team-multichannel-koboldmaki @tudor2004
=> CHANGE renaming of property dependencies

src/ResultFields/RakutenDE.php
=> FIX param was misplaced

src/Generators/GoogleShopping.php
=> ADD added base price data

src/Generators/GoogleShopping.php
=> FIX base price will only be filled if it is more than one unit

src/Helper/ElasticExportHelper.php
@jschaakplenty 
@Desentyer 
@simonamoise
=> ADD convert relative paths to absolute paths

src/Generators/GoogleShopping.php
=> FIX property export. F#34703

src/Generators/GoogleShopping.php, src/ResultFields/GoogleShopping.php
=> FIX using apiCondition instead of condition

src/Generators/RakutenDE.php
=> FIX attribute combination order.

src/Generators/KaufluxDE.php, src/ResultFields/KaufluxDE.php
=> image fix kauflux

src/Helper/ElasticExportHelper.php
=> FIX add string cast to prevent further fatals

src/Filters/RakutenDE.php, src/Generators/RakutenDE.php, src/ResultFields/RakutenDE.php
=> CHANGE use market account setting and rakuten constant instead of id

src/Helper/ElasticExportHelper.php
=> FIX disturbed pluginapp() usage

src/Generators/GuenstigerDE.php
@plentymarkets/team-multichannel
=> FIX number_format expected float as param
